### PR TITLE
Add support for registry authentication

### PR DESCRIPTION
**Pull request by trecloux**
This pull request add support for registry authentication.

### CODE REVIEW

**Comment by yan-foto** [comment]
The basic authentication has already been implemented in this branch: https://github.com/fraunhoferfokus/deckschrubber/tree/feature/basic-auth as requested in our very first issue #1 . However, no one was willing to test to it. Could you take a look? thanks 😅

**Comment by trecloux** [comment]
Hi @yan-foto ,
Sorry, I missed this issue/branch.
I rebased/tested/fixed the `basic-auth` branch in this branch : https://github.com/auchanretailfrance/deckschrubber/tree/feature/basic-auth-testing.
The authenticated transport was not provided to the registry client.
With the fix, my testing was successful against a nexus registry.

**Comment by yan-foto** [comment]
Wow! That was quick 😄 Thanks for your the PR. Could you please give a little time to merge it?

**Comment by trecloux** [comment]
To be sure: do you want me to submit a PR based on https://github.com/auchanretailfrance/deckschrubber/tree/feature/basic-auth-testing branch ?

**Comment by yan-foto** [comment]
Yes please.

**Comment by trecloux** [comment]
I created https://github.com/fraunhoferfokus/deckschrubber/pull/23
Closing this pull request.

**Pull request closed without merging**
