### PR TITLE
Set up go module

### PR DESCRIPTION
**Pull request by homburg**
Make repo go-gettable/buildable when using go modules

### CODE REVIEW

**Comment by yan-foto** [comment]
Thanks Thomas for the PR! I will merge this as ASAP. Just a quick question: are those `indirect` dependencies there because Logrus and Docker are not go modules?

**Comment by homburg** [comment]
@yan-foto NP! The work was basically running `go mod init` and comitting :-)

As I understand it there's `direct` and `indirect` dependencies.

The `direct` dependencies are those directly imported in this project. And the `indirect` dependencies are the dependencies of the `direct` dependencies.

I don't think it makes a difference if the `direct` dependencies are go module or not.

**Comment by yan-foto** [comment]
Sine we have no proper tests (shame on me!), the last step is to have your PRs tested. If you have already done this, I'll just merge both.

**Comment by homburg** [comment]
Hi @yan-foto the PR is tested and ready for merge 👍

**Comment by jgimenez** [comment]
So what's the status of this one, can it be merged?

**Comment by yan-foto** [comment]
@jgimenez just merged it. But due to my laziness/business that lead to such late merging, some items might be outdated. Please feel free to update in your PR.

**Pull request merged**
